### Analysis of Azure Pricing details, 
#### source JSON file https://prices.azure.com/api/retail/prices?api-version=2021-10-01-preview&meterRegion=%E2%80%99primary%E2%80%99

In [3]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB 7.5 MB/s eta 0:00:01    |████████████████▋               | 6.0 MB 7.5 MB/s eta 0:00:01
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /opt/app-root/lib/python3.6/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: numpy>=1.15 in /opt/app-root/lib/python3.6/site-packages (from matplotlib) (1.19.4)
Requirement already satisfied: python-dateutil>=2.1 in /opt/app-root/lib/python3.6/site-packages (from matplotlib) (2.8.1)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 31.8 MB/s eta 0:00:01
Collecting pillow>=6.2.0
  Downloading Pillow-8.4.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 32.0 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib) (1.15.0)
Installing collected packages: pillow, kiwisolver, cycler, matplotlib
Successfully installed cycler-0.11.0 kiwisolver-1.3.1 matplotlib-3.3.4 pillow-8.4.0
WARNING: You are using pip version 20.3.1; however, version 21.3.1 is available.
You should consider upgrading via the '/opt/app-root/bin/python3.6 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [4]:
import json as json
import pandas as pd
import matplotlib.pyplot as plt
from collections import defaultdict
import requests

#### Access the API end point for 'Vitual Machine' and create JSON file ../data/raw/

In [5]:
r = requests.get('https://prices.azure.com/api/retail/prices?$filter=serviceName eq \'Virtual Machines\'')
with open('../../data/raw/azure_vm.json','w') as fd:
    fd.write(r.text)

In [6]:
df = pd.read_json("../../data/raw/azure_vm.json")
df.head()

,BillingCurrency,CustomerEntityId,CustomerEntityType,Items,NextPageLink,Count
0,USD,Default,Retail,"{'currencyCode': 'USD', 'tierMinimumUnits': 0....",https://prices.azure.com:443/api/retail/prices...,100
1,USD,Default,Retail,"{'currencyCode': 'USD', 'tierMinimumUnits': 0....",https://prices.azure.com:443/api/retail/prices...,100
2,USD,Default,Retail,"{'currencyCode': 'USD', 'tierMinimumUnits': 0....",https://prices.azure.com:443/api/retail/prices...,100
3,USD,Default,Retail,"{'currencyCode': 'USD', 'tierMinimumUnits': 0....",https://prices.azure.com:443/api/retail/prices...,100
4,USD,Default,Retail,"{'currencyCode': 'USD', 'tierMinimumUnits': 0....",https://prices.azure.com:443/api/retail/prices...,100

#### Understand shape of data

In [7]:
print("Shape of the data\n\n", df.shape)
print("\n\n")
print("Is null?\n\n", df.isnull().sum())
print("\n\n")
print("Columnwise Datatype\n\n", df.dtypes)
df.describe()

Shape of the data

 (100, 6)



Is null?

 BillingCurrency       0
CustomerEntityId      0
CustomerEntityType    0
Items                 0
NextPageLink          0
Count                 0
dtype: int64



Columnwise Datatype

 BillingCurrency       object
CustomerEntityId      object
CustomerEntityType    object
Items                 object
NextPageLink          object
Count                  int64
dtype: object

       Count
count  100.0
mean   100.0
std      0.0
min    100.0
25%    100.0
50%    100.0
75%    100.0
max    100.0

In [33]:
#### Split data into multiple components, create series out of dataframes, List "Items" is carrying actual data items

In [44]:
df_items = df["Items"]
df_items = df_items.fillna("NA")
type(df_items)
dfi_l=len(df_items)
dfi_l

100

In [45]:
#print dict
df_items

0     {'currencyCode': 'USD', 'tierMinimumUnits': 0....
1     {'currencyCode': 'USD', 'tierMinimumUnits': 0....
2     {'currencyCode': 'USD', 'tierMinimumUnits': 0....
3     {'currencyCode': 'USD', 'tierMinimumUnits': 0....
4     {'currencyCode': 'USD', 'tierMinimumUnits': 0....
                            ...
95    {'currencyCode': 'USD', 'tierMinimumUnits': 0....
96    {'currencyCode': 'USD', 'tierMinimumUnits': 0....
97    {'currencyCode': 'USD', 'tierMinimumUnits': 0....
98    {'currencyCode': 'USD', 'tierMinimumUnits': 0....
99    {'currencyCode': 'USD', 'tierMinimumUnits': 0....
Name: Items, Length: 100, dtype: object

#### Normalize data into tabular format

In [46]:
dfi_normalize = pd.json_normalize(df_items)
(dfi_normalize).fillna("NA")
dfi_normalize

,currencyCode,tierMinimumUnits,retailPrice,unitPrice,armRegionName,location,effectiveStartDate,meterId,meterName,productId,...,productName,skuName,serviceName,serviceId,serviceFamily,unitOfMeasure,type,isPrimaryMeterRegion,armSkuName,reservationTerm
0,USD,0.0,0.542506,0.542506,southindia,IN South,2022-03-01T00:00:00Z,000009d0-057f-5f2b-b7e9-9e26add324a8,D14/DS14 Spot,DZH318Z0BPVW,...,Virtual Machines D Series Windows,D14 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,Consumption,True,Standard_D14,NaN
1,USD,0.0,0.262752,0.262752,southindia,IN South,2022-03-01T00:00:00Z,000009d0-057f-5f2b-b7e9-9e26add324a8,D14/DS14 Spot,DZH318Z0BPVW,...,Virtual Machines D Series Windows,D14 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_D14,NaN
2,USD,0.0,1.468006,1.468006,eastasia,AP East,2022-03-01T00:00:00Z,00014e7d-fff9-54dd-962e-4e992887ad3c,D64s v5 Spot,DZH318Z08M9T,...,Virtual Machines Dsv5 Series Windows,Standard_D64s_v5 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,Consumption,True,Standard_D64s_v5,NaN
3,USD,0.0,0.865075,0.865075,eastasia,AP East,2022-03-01T00:00:00Z,00014e7d-fff9-54dd-962e-4e992887ad3c,D64s v5 Spot,DZH318Z08M9T,...,Virtual Machines Dsv5 Series Windows,Standard_D64s_v5 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_D64s_v5,NaN
4,USD,0.0,0.062988,0.062988,uknorth,UK North,2019-10-16T00:00:00Z,0001e46a-9285-5fa8-b48a-240e307a24f7,A3 Spot,DZH318Z0BPVJ,...,Virtual Machines A Series Windows,A3 Spot,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_A3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,USD,0.0,0.272000,0.272000,uaecentral,AE Central,2021-11-01T00:00:00Z,001fa4dd-bbe2-5502-b172-8a1af70ea8b8,D2ds v5,DZH318Z08MC5,...,Virtual Machines Ddsv5 Series Windows,Standard_D2ds_v5,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,Consumption,True,Standard_D2ds_v5,NaN
96,USD,0.0,0.180000,0.180000,uaecentral,AE Central,2021-11-01T00:00:00Z,001fa4dd-bbe2-5502-b172-8a1af70ea8b8,D2ds v5,DZH318Z08MC5,...,Virtual Machines Ddsv5 Series Windows,Standard_D2ds_v5,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_D2ds_v5,NaN
97,USD,0.0,1.949000,1.949000,uksouth,UK South,2021-11-01T00:00:00Z,001fa6ba-405f-5854-9dd5-5ecd8a7d7ef3,D48s v5 Low Priority,DZH318Z08M9T,...,Virtual Machines Dsv5 Series Windows,Standard_D48s_v5 Low Priority,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,Consumption,True,Standard_D48s_v5,NaN
98,USD,0.0,0.533000,0.533000,uksouth,UK South,2021-11-01T00:00:00Z,001fa6ba-405f-5854-9dd5-5ecd8a7d7ef3,D48s v5 Low Priority,DZH318Z08M9T,...,Virtual Machines Dsv5 Series Windows,Standard_D48s_v5 Low Priority,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_D48s_v5,NaN
99,USD,0.0,32.064000,32.064000,eastus2,US East 2,2021-01-01T00:00:00Z,00204db1-b465-59e2-baa7-bc6b848c5b78,M192idms_v2,DZH318Z08LV0,...,Virtual Machines MdSv2 Series Windows,M192idms_v2,Virtual Machines,DZH313Z7MMC8,Compute,1 Hour,DevTestConsumption,True,Standard_M192idms_v2,NaN

#### Understand unique Product Names from Items

In [53]:
pd.unique(dfi_normalize["skuName"])
#pd.Series((dfi_s["productName"])).unique()
#pd.Series((dfi_normalize["armRegionName"])).unique()

array(['D14 Spot', 'Standard_D64s_v5 Spot', 'A3 Spot',
       'Standard_E2bds_v5 Spot', 'D2 v4 Low Priority', 'E2s v5 Spot',
       'Standard_D16s_v5', 'E16-8ads v5 Spot', 'D14 v2', 'DS14 v2', 'A2',
       'E8-2s v4 Low Priority', 'Standard_D96_v5 Low Priority',
       'F16s Spot', 'DS4 v2 Spot', 'Standard_D64ds_v5',
       'Standard_E20d_v5 Low Priority', 'Easv4 Type2',
       'Standard_DC8as_v5 Low Priority', 'E20 v3 Low Priority',
       'E20s v3 Low Priority', 'A3', 'F16 Spot', 'E32 v4 Spot',
       'E104ids v5 Low Priority', 'Standard_D4ds_v5',
       'Standard_D16ds_v5 Spot', 'HC44-32rs Spot', 'E64-16s v4 Spot',
       'D64s v4', 'E64s v4', 'E20ds v4 Low Priority', 'M416s v2 Spot',
       'E64 v4', 'E4ds v5 Low Priority', 'E4-2ds v5 Low Priority',
       'D5 v2 Spot', 'DS13 Low Priority', 'D13 Low Priority',
       'NV4as v4 Spot', 'E8-4ads v5 Low Priority', 'E48s v5 Spot',
       'M128 Low Priority', 'D16s v3 Spot', 'Standard_E96_v5',
       'E64 v3 Spot', 'E4s v5 Low Priority', 'E4-2s v5 Low Priority',
       'E48 v3 Low Priority', 'E48s v3 Low Priority', 'E16 v4 Spot',
       'E16ds v4 Spot', 'E48ds v4 Low Priority', 'D64ds v4 Low Priority',
       'E8-2ds v4 Spot', 'Standard_D2ds_v5',
       'Standard_D48s_v5 Low Priority', 'M192idms_v2'], dtype=object)

In [91]:
dfi_s=dfi_normalize[["armRegionName","productName","skuName","retailPrice","currencyCode","serviceName","serviceFamily"]]
#dfi_s=dfi_normalize[["armRegionName","productName","skuName","retailPrice"]]
dfi_s

,armRegionName,productName,skuName,retailPrice,currencyCode,serviceName,serviceFamily
0,southindia,Virtual Machines D Series Windows,D14 Spot,0.542506,USD,Virtual Machines,Compute
1,southindia,Virtual Machines D Series Windows,D14 Spot,0.262752,USD,Virtual Machines,Compute
2,eastasia,Virtual Machines Dsv5 Series Windows,Standard_D64s_v5 Spot,1.468006,USD,Virtual Machines,Compute
3,eastasia,Virtual Machines Dsv5 Series Windows,Standard_D64s_v5 Spot,0.865075,USD,Virtual Machines,Compute
4,uknorth,Virtual Machines A Series Windows,A3 Spot,0.062988,USD,Virtual Machines,Compute
...,...,...,...,...,...,...,...
95,uaecentral,Virtual Machines Ddsv5 Series Windows,Standard_D2ds_v5,0.272000,USD,Virtual Machines,Compute
96,uaecentral,Virtual Machines Ddsv5 Series Windows,Standard_D2ds_v5,0.180000,USD,Virtual Machines,Compute
97,uksouth,Virtual Machines Dsv5 Series Windows,Standard_D48s_v5 Low Priority,1.949000,USD,Virtual Machines,Compute
98,uksouth,Virtual Machines Dsv5 Series Windows,Standard_D48s_v5 Low Priority,0.533000,USD,Virtual Machines,Compute
99,eastus2,Virtual Machines MdSv2 Series Windows,M192idms_v2,32.064000,USD,Virtual Machines,Compute

#### Group by columns ('armRegionName','productName','skuName','serviceName','serviceFamily') to get region wise Max Price and Min Price

In [93]:
#data = dfi_s.groupby('productName').transform(lambda x: (x - x.min()) / x.max()- x.min())
#grouper = dfi_s.groupby(['armRegionName','productName','skuName'])['retailPrice'].agg(['max','min'])
result = dfi_s.groupby(['armRegionName','productName','skuName','serviceName','serviceFamily']).agg(
    maxPrice=('retailPrice','max'),minPrice=('retailPrice','min'))

result

                                                                                                                             maxPrice  \
armRegionName      productName                            skuName                        serviceName      serviceFamily
australiacentral   Virtual Machines Edsv4 Series Windows  E8-2ds v4 Spot                 Virtual Machines Compute            0.184710
australiacentral2  Virtual Machines Esv5 Series           E48s v5 Spot                   Virtual Machines Compute            1.449600
australiaeast      Virtual Machines Esv4 Series Windows   E64-16s v4 Spot                Virtual Machines Compute            2.057530
australiasoutheast Virtual Machines Eadsv5 Series Windows E16-8ads v5 Spot               Virtual Machines Compute            0.537088
                   Virtual Machines F Series Windows      F16 Spot                       Virtual Machines Compute            0.403024
brazilsouth        Virtual Machines A Series Basic        A2                             Virtual Machines Compute            0.112000
                   Virtual Machines MSv2 Series Windows   M416s v2 Spot                  Virtual Machines Compute           17.373000
canadacentral      Virtual Machines D Series Windows      D13 Low Priority               Virtual Machines Compute            0.456000
                   Virtual Machines DS Series Windows     DS13 Low Priority              Virtual Machines Compute            0.456000
                   Virtual Machines Edsv4 Series Windows  E20ds v4 Low Priority          Virtual Machines Compute            1.000000
canadaeast         Virtual Machines Esv5 Series           E4-2s v5 Low Priority          Virtual Machines Compute            0.055200
                                                          E4s v5 Low Priority            Virtual Machines Compute            0.055200
centralus          Virtual Machines A Series Windows      A3 Spot                        Virtual Machines Compute            0.054000
                   Virtual Machines Esv4 Series           E8-2s v4 Low Priority          Virtual Machines Compute            0.114000
eastasia           Virtual Machines Dsv5 Series Windows   Standard_D64s_v5 Spot          Virtual Machines Compute            1.468006
eastus             DCasv5-series Linux                    Standard_DC8as_v5 Low Priority Virtual Machines Compute            0.108000
eastus2            Virtual Machines Dsv5 Series Windows   Standard_D16s_v5               Virtual Machines Compute            1.504000
                   Virtual Machines Eadsv5 Series         E8-4ads v5 Low Priority        Virtual Machines Compute            0.105000
                   Virtual Machines MdSv2 Series Windows  M192idms_v2                    Virtual Machines Compute           32.064000
japaneast          Virtual Machines A Series Windows      A3                             Virtual Machines Compute            0.424000
                   Virtual Machines Edsv5 Series          E104ids v5 Low Priority        Virtual Machines Compute            1.991000
                   Virtual Machines Edv5 Series           Standard_E20d_v5 Low Priority  Virtual Machines Compute            0.348000
japanwest          Virtual Machines Ddsv5 Series Windows  Standard_D16ds_v5 Spot         Virtual Machines Compute            0.389939
                   Virtual Machines Esv4 Series Windows   E64s v4                        Virtual Machines Compute            8.294000
koreasouth         Easv4 Series Dedicated Host            Easv4 Type2                    Virtual Machines Compute        77890.000000
                   Virtual Machines Dv5 Series Windows    Standard_D96_v5 Low Priority   Virtual Machines Compute            3.886000
northcentralus     Virtual Machines DSv2 promo Series     DS14 v2                        Virtual Machines Compute            1.482000
                   Virtual Machines Dv2 promo Series      D14 v2                         Virtual Machines Compute            1.482000
northeurope        Virtual Machines Esv5 Series           E2s v5 Spot                    Virtual Machines Compute            0.036547
                   Virtual Machines Ev5 Series            Standard_E96_v5                Virtual Machines Compute        67588.000000
southafricawest    Virtual Machines ESv3 Series           E20s v3 Low Priority           Virtual Machines Compute            0.420000
                   Virtual Machines Edsv4 Series Windows  E16ds v4 Spot                  Virtual Machines Compute            0.538474
                   Virtual Machines Ev3 Series            E20 v3 Low Priority            Virtual Machines Compute            0.420000
southcentralus     Virtual Machines Ev4 Series            E64 v4                         Virtual Machines Compute        48318.000000
southeastasia      Virtual Machines HCS Series            HC44-32rs Spot                 Virtual Machines Compute            0.411800
southindia         Virtual Machines D Series Windows      D14 Spot                       Virtual Machines Compute            0.542506
                   Virtual Machines Dv2 Series            D5 v2 Spot                     Virtual Machines Compute            0.181440
                   Virtual Machines MS Series Windows     M128 Low Priority              Virtual Machines Compute           10.440000
switzerlandnorth   Virtual Machines Ddsv5 Series Windows  Standard_D4ds_v5               Virtual Machines Compute            0.483000
uaecentral         Virtual Machines Ddsv5 Series Windows  Standard_D2ds_v5               Virtual Machines Compute            0.272000
                   Virtual Machines Ev4 Series            E16 v4 Spot                    Virtual Machines Compute            0.157200
                                                          E32 v4 Spot                    Virtual Machines Compute            0.314500
uaenorth           Virtual Machines DSv3 Series Windows   D16s v3 Spot                   Virtual Machines Compute            0.338691
uknorth            Virtual Machines A Series Windows      A3 Spot                        Virtual Machines Compute            0.190000
                   Virtual Machines Ev3 Series Windows    E64 v3 Spot                    Virtual Machines Compute            3.224400
uksouth            Virtual Machines Dsv5 Series Windows   Standard_D48s_v5 Low Priority  Virtual Machines Compute            1.949000
usgovarizona       Virtual Machines Dsv4 Series           D64s v4                        Virtual Machines Compute        38667.000000
                   Virtual Machines NVasv4 Series         NV4as v4 Spot                  Virtual Machines Compute            0.039110
usgovtexas         Virtual Machines FS Series Windows     F16s Spot                      Virtual Machines Compute            0.341510
westcentralus      Virtual Machines Edsv5 Series Windows  E4-2ds v5 Low Priority         Virtual Machines Compute            0.212000
                                                          E4ds v5 Low Priority           Virtual Machines Compute            0.212000
westeurope         Virtual Machines FS Series Windows     F16s Spot                      Virtual Machines Compute            0.571308
westindia          Virtual Machines DSv2 Series           DS4 v2 Spot                    Virtual Machines Compute            0.090720
                   Virtual Machines Dv4 Series            D2 v4 Low Priority             Virtual Machines Compute            0.023600
                   Virtual Machines Edsv4 Series Windows  E48ds v4 Low Priority          Virtual Machines Compute            2.551000
westus             Virtual Machines Ebdsv5 Series         Standard_E2bds_v5 Spot         Virtual Machines Compute            0.075600
westus2            Virtual Machines Ddsv4 Series          D64ds v4 Low Priority          Virtual Machines Compute            0.723000
                   Virtual Machines Ddsv5 Series          Standard_D64ds_v5              Virtual Machines Compute        36111.000000
                   Virtual Machines ESv3 Series Windows   E48s v3 Low Priority           Virtual Machines Compute            2.093000
                   Virtual Machines Ev3 Series Windows    E48 v3 Low Priority            Virtual Machines Compute            2.093000

                                                                                                                          minPrice
armRegionName      productName                            skuName                        serviceName      serviceFamily
australiacentral   Virtual Machines Edsv4 Series Windows  E8-2ds v4 Spot                 Virtual Machines Compute         0.069600
australiacentral2  Virtual Machines Esv5 Series           E48s v5 Spot                   Virtual Machines Compute         1.449600
australiaeast      Virtual Machines Esv4 Series Windows   E64-16s v4 Spot                Virtual Machines Compute         0.852365
australiasoutheast Virtual Machines Eadsv5 Series Windows E16-8ads v5 Spot               Virtual Machines Compute         0.435840
                   Virtual Machines F Series Windows      F16 Spot                       Virtual Machines Compute         0.157550
brazilsouth        Virtual Machines A Series Basic        A2                             Virtual Machines Compute         0.112000
                   Virtual Machines MSv2 Series Windows   M416s v2 Spot                  Virtual Machines Compute         9.668100
canadacentral      Virtual Machines D Series Windows      D13 Low Priority               Virtual Machines Compute         0.155000
                   Virtual Machines DS Series Windows     DS13 Low Priority              Virtual Machines Compute         0.155000
                   Virtual Machines Edsv4 Series Windows  E20ds v4 Low Priority          Virtual Machines Compute         0.316000
canadaeast         Virtual Machines Esv5 Series           E4-2s v5 Low Priority          Virtual Machines Compute         0.055200
                                                          E4s v5 Low Priority            Virtual Machines Compute         0.055200
centralus          Virtual Machines A Series Windows      A3 Spot                        Virtual Machines Compute         0.030648
                   Virtual Machines Esv4 Series           E8-2s v4 Low Priority          Virtual Machines Compute         0.114000
eastasia           Virtual Machines Dsv5 Series Windows   Standard_D64s_v5 Spot          Virtual Machines Compute         0.865075
eastus             DCasv5-series Linux                    Standard_DC8as_v5 Low Priority Virtual Machines Compute         0.108000
eastus2            Virtual Machines Dsv5 Series Windows   Standard_D16s_v5               Virtual Machines Compute         0.768000
                   Virtual Machines Eadsv5 Series         E8-4ads v5 Low Priority        Virtual Machines Compute         0.105000
                   Virtual Machines MdSv2 Series Windows  M192idms_v2                    Virtual Machines Compute        32.064000
japaneast          Virtual Machines A Series Windows      A3                             Virtual Machines Compute         0.324000
                   Virtual Machines Edsv5 Series          E104ids v5 Low Priority        Virtual Machines Compute         1.991000
                   Virtual Machines Edv5 Series           Standard_E20d_v5 Low Priority  Virtual Machines Compute         0.348000
japanwest          Virtual Machines Ddsv5 Series Windows  Standard_D16ds_v5 Spot         Virtual Machines Compute         0.239206
                   Virtual Machines Esv4 Series Windows   E64s v4                        Virtual Machines Compute         5.350000
koreasouth         Easv4 Series Dedicated Host            Easv4 Type2                    Virtual Machines Compute         7.603000
                   Virtual Machines Dv5 Series Windows    Standard_D96_v5 Low Priority   Virtual Machines Compute         1.060000
northcentralus     Virtual Machines DSv2 promo Series     DS14 v2                        Virtual Machines Compute         1.482000
                   Virtual Machines Dv2 promo Series      D14 v2                         Virtual Machines Compute         1.482000
northeurope        Virtual Machines Esv5 Series           E2s v5 Spot                    Virtual Machines Compute         0.036547
                   Virtual Machines Ev5 Series            Standard_E96_v5                Virtual Machines Compute         6.768000
southafricawest    Virtual Machines ESv3 Series           E20s v3 Low Priority           Virtual Machines Compute         0.420000
                   Virtual Machines Edsv4 Series Windows  E16ds v4 Spot                  Virtual Machines Compute         0.196983
                   Virtual Machines Ev3 Series            E20 v3 Low Priority            Virtual Machines Compute         0.420000
southcentralus     Virtual Machines Ev4 Series            E64 v4                         Virtual Machines Compute         4.838000
southeastasia      Virtual Machines HCS Series            HC44-32rs Spot                 Virtual Machines Compute         0.411800
southindia         Virtual Machines D Series Windows      D14 Spot                       Virtual Machines Compute         0.262752
                   Virtual Machines Dv2 Series            D5 v2 Spot                     Virtual Machines Compute         0.181440
                   Virtual Machines MS Series Windows     M128 Low Priority              Virtual Machines Compute         4.041000
switzerlandnorth   Virtual Machines Ddsv5 Series Windows  Standard_D4ds_v5               Virtual Machines Compute         0.150000
uaecentral         Virtual Machines Ddsv5 Series Windows  Standard_D2ds_v5               Virtual Machines Compute         0.180000
                   Virtual Machines Ev4 Series            E16 v4 Spot                    Virtual Machines Compute         0.157200
                                                          E32 v4 Spot                    Virtual Machines Compute         0.314500
uaenorth           Virtual Machines DSv3 Series Windows   D16s v3 Spot                   Virtual Machines Compute         0.129024
uknorth            Virtual Machines A Series Windows      A3 Spot                        Virtual Machines Compute         0.062988
                   Virtual Machines Ev3 Series Windows    E64 v3 Spot                    Virtual Machines Compute         1.022888
uksouth            Virtual Machines Dsv5 Series Windows   Standard_D48s_v5 Low Priority  Virtual Machines Compute         0.533000
usgovarizona       Virtual Machines Dsv4 Series           D64s v4                        Virtual Machines Compute         3.872000
                   Virtual Machines NVasv4 Series         NV4as v4 Spot                  Virtual Machines Compute         0.039110
usgovtexas         Virtual Machines FS Series Windows     F16s Spot                      Virtual Machines Compute         0.341510
westcentralus      Virtual Machines Edsv5 Series Windows  E4-2ds v5 Low Priority         Virtual Machines Compute         0.069100
                                                          E4ds v5 Low Priority           Virtual Machines Compute         0.069100
westeurope         Virtual Machines FS Series Windows     F16s Spot                      Virtual Machines Compute         0.210434
westindia          Virtual Machines DSv2 Series           DS4 v2 Spot                    Virtual Machines Compute         0.090720
                   Virtual Machines Dv4 Series            D2 v4 Low Priority             Virtual Machines Compute         0.023600
                   Virtual Machines Edsv4 Series Windows  E48ds v4 Low Priority          Virtual Machines Compute         0.834000
westus             Virtual Machines Ebdsv5 Series         Standard_E2bds_v5 Spot         Virtual Machines Compute         0.075600
westus2            Virtual Machines Ddsv4 Series          D64ds v4 Low Priority          Virtual Machines Compute         0.723000
                   Virtual Machines Ddsv5 Series          Standard_D64ds_v5              Virtual Machines Compute         3.616000
                   Virtual Machines ESv3 Series Windows   E48s v3 Low Priority           Virtual Machines Compute         0.605000
                   Virtual Machines Ev3 Series Windows    E48 v3 Low Priority            Virtual Machines Compute         0.605000

#### Data analysis to understand service prices above 5000 USD

In [22]:
high_price= dfi_s[dfi_s["retailPrice"] > 5000 ]
high_price

,armRegionName,productName,retailPrice,currencyCode,serviceName,serviceFamily
22,westus2,Virtual Machines Ddsv5 Series,36111.0,USD,Virtual Machines,Compute
23,westus2,Virtual Machines Ddsv5 Series,18689.0,USD,Virtual Machines,Compute
28,koreasouth,Easv4 Series Dedicated Host,77890.0,USD,Virtual Machines,Compute
29,koreasouth,Easv4 Series Dedicated Host,39231.0,USD,Virtual Machines,Compute
47,usgovarizona,Virtual Machines Dsv4 Series,38667.0,USD,Virtual Machines,Compute
48,usgovarizona,Virtual Machines Dsv4 Series,20012.0,USD,Virtual Machines,Compute
56,southcentralus,Virtual Machines Ev4 Series,48318.0,USD,Virtual Machines,Compute
57,southcentralus,Virtual Machines Ev4 Series,25007.0,USD,Virtual Machines,Compute
74,northeurope,Virtual Machines Ev5 Series,67588.0,USD,Virtual Machines,Compute
76,northeurope,Virtual Machines Ev5 Series,34980.0,USD,Virtual Machines,Compute